AWSTemplateFormatVersion:               "2010-09-09"
Description:                            "A Lambda function that cleans up Elasticsearch indexes using unsigned requests"

Parameters:

  LambdaName:
    Description:                        "Name of the Lambda function"
    Type:                               "String"
    Default:                            "ElasticsearchIndexCleanup"

  SourceBucket:
    Description:                        "The S3 bucket where you uploaded the Lamdba deployment bundle"
    Type:                               "String"

  SourceKey:
    Description:                        "The path in that bucket to the Lambda deployment bundle"
    Type:                               "String"

  Schedule:
    Description:                        "Scheduling expression for trigger (cron or rate)"
    Type:                               "String"
    Default:                            "cron(0 0 * * ? *)"

  ElasticsearchHostname:
    Description:                        "The fully-qualified hostname of your Elasticsearch cluster"
    Type:                               "String"

  IndexPrefix:
    Description:                        "The prefix used for indexes that will be cleaned by this Lambda"
    Type:                               "String"

  IndexCount:
    Description:                        "The maximum number of those indexes that are permitted"
    Type:                               "String"


Resources:

  ExecutionRole:
    Type:                               "AWS::IAM::Role"
    Properties:
      Path:                             "/lambda/"
      RoleName:                         !Sub "${LambdaName}-ExecutionRole-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version:                        "2012-10-17"
        Statement:
          Effect:                       "Allow"
          Principal:
            Service:                    "lambda.amazonaws.com"
          Action:                       "sts:AssumeRole"
      Policies:
        -
          PolicyName:                   "InternalLogging"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
              Effect:                   "Allow"
              Action:
                -                       "logs:CreateLogStream"
                -                       "logs:PutLogEvents"
              Resource:                 [ !GetAtt LogGroup.Arn ]


  LogGroup:
    Type:                               "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName:                     !Sub "/aws/lambda/${LambdaName}"
      RetentionInDays:                  30


  LambdaFunction:
    Type:                               "AWS::Lambda::Function"
    Properties: 
      FunctionName:                     !Ref LambdaName
      Description:                      !Sub "Maintains a specified number of indexes in Elasticsearch cluster ${ElasticsearchHostname}"
      Role:                             !GetAtt ExecutionRole.Arn
      Runtime:                          "python3.8"
      Handler:                          "lambda_function.lambda_handler"
      Code: 
        S3Bucket:                       !Ref SourceBucket
        S3Key:                          !Ref SourceKey
      MemorySize:                       256
      Timeout:                          30
      Environment:
        Variables:
          ELASTIC_SEARCH_HOSTNAME:      !Ref ElasticsearchHostname
          INDEX_PREFIX:                 !Ref IndexPrefix
          NUM_INDEXES_TO_KEEP:          !Ref IndexCount

  
  LambdaPermission:
    Type:                               "AWS::Lambda::Permission"
    Properties: 
      Action:                           "lambda:InvokeFunction"
      FunctionName:                     !Ref LambdaFunction
      Principal:                        "events.amazonaws.com"
      SourceArn:                        !GetAtt InvocationSchedule.Arn


  InvocationSchedule:
    Type:                               "AWS::Events::Rule"
    Properties: 
      Description:                      !Sub "Invokes the ${LambdaName} Lambda function"
      ScheduleExpression:               !Ref Schedule
      State:                            "ENABLED"
      Targets: 
        - Arn:                          !GetAtt LambdaFunction.Arn
          Id:                           !Sub "Invoke-${LambdaName}"
